// Auto-generated file - do not edit manually
// This file is generated by scripts/discover-recipes.js
// It lists all .md files found in public/recipes/

export const recipeFiles = [
  "бъркана-зелена-баница.md"
];

export default recipeFiles;
