const fs = require('fs');
const path = require('path');

const recipesDir = path.join(__dirname, '..', 'public', 'recipes');
const outputFile = path.join(__dirname, '..', 'src', 'recipes', 'discovered.js');

// Discover all .md files in the recipes directory
function discoverRecipes() {
  try {
    const files = fs.readdirSync(recipesDir);
    const mdFiles = files.filter(file => 
      file.endsWith('.md') && 
      file !== 'README.md' && 
      !file.startsWith('.')
    );
    
    // Generate the module content
    const moduleContent = `// Auto-generated file - do not edit manually
// This file is generated by scripts/discover-recipes.js
// It lists all .md files found in public/recipes/

export const recipeFiles = ${JSON.stringify(mdFiles, null, 2)};

export default recipeFiles;
`;

    // Write the generated module
    fs.writeFileSync(outputFile, moduleContent, 'utf8');
    console.log(`✓ Discovered ${mdFiles.length} recipe files:`);
    mdFiles.forEach(file => console.log(`  - ${file}`));
    console.log(`✓ Generated ${outputFile}`);
  } catch (error) {
    console.error('Error discovering recipes:', error);
    process.exit(1);
  }
}

discoverRecipes();

