import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, User, UtensilsCrossed, FileDown, ExternalLink } from 'lucide-react';
import { parseRecipeMarkdown, generateRecipeMarkdown, generateRecipeFilename, downloadMarkdownFile } from './utils/recipeParser';
import { generateRecipePDF, generateAllRecipesPDF } from './utils/pdfGenerator';
import { recipeFiles } from './recipes/discovered';
import { getMealTypesFromRecipes, getMealTypeLabel, getDefaultMealTypes } from './utils/mealTypes';
import './RecipeBook.css';

const RECIPES_DIR = '/recipes';

function RecipeBook() {
  const [recipes, setRecipes] = useState([]);
  const [mealTypes, setMealTypes] = useState(getDefaultMealTypes());
  const [loading, setLoading] = useState(true);
  const [selectedMealType, setSelectedMealType] = useState('all');
  const [formData, setFormData] = useState({
    title: '',
    mealType: 'breakfast',
    author: '',
    photo: '',
    content: ''
  });

  useEffect(() => {
    loadRecipes();
  }, []);

  const loadRecipes = async () => {
    setLoading(true);
    try {
      // Use the auto-discovered recipe files list
      // This is generated by scripts/discover-recipes.js at build time
      
      // Load each recipe markdown file
      const loadedRecipes = await Promise.all(
        recipeFiles.map(async (filename) => {
          try {
            const response = await fetch(`${RECIPES_DIR}/${filename}`);
            if (!response.ok) {
              console.warn(`Could not load ${filename}`);
              return null;
            }
            const markdown = await response.text();
            const recipe = parseRecipeMarkdown(markdown);
            return {
              id: filename,
              filename: filename,
              ...recipe
            };
          } catch (error) {
            console.error(`Error loading ${filename}:`, error);
            return null;
          }
        })
      );

      // Filter out null values
      const validRecipes = loadedRecipes.filter(recipe => recipe !== null);
      setRecipes(validRecipes);
      
      // Extract meal types dynamically from loaded recipes
      const dynamicMealTypes = getMealTypesFromRecipes(validRecipes);
      if (dynamicMealTypes.length > 0) {
        setMealTypes(dynamicMealTypes);
      }
    } catch (error) {
      console.error('Error loading recipes:', error);
      setRecipes([]);
    } finally {
      setLoading(false);
    }
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    
    if (!formData.title || !formData.author || !formData.content) {
      alert('Моля, попълнете всички задължителни полета!');
      return;
    }

    const newRecipe = {
      id: Date.now().toString(),
      ...formData
    };

    // Generate markdown content
    const markdownContent = generateRecipeMarkdown(newRecipe);
    const filename = generateRecipeFilename(formData.title);
    
    // Download the markdown file
    downloadMarkdownFile(markdownContent, filename);
    
    // Show success message with instructions
    alert(
      `Рецептата е генерирана и изтеглена!\n\n` +
      `Файл: ${filename}\n\n` +
      `Моля, поставете файла в папката public/recipes/ и рестартирайте приложението за да се покаже автоматично.`
    );
    
    // Reset form
    setFormData({
      title: '',
      mealType: 'breakfast',
      author: '',
      photo: '',
      content: ''
    });
    
    setShowForm(false);
    
    // Auto-refresh recipes after a short delay to allow user to add the file
    setTimeout(() => {
      loadRecipes();
    }, 1000);
  };


  const handleDownloadPDF = async (recipe) => {
    const mealTypeLabel = getMealTypeLabel(recipe.mealType);
    try {
      await generateRecipePDF(recipe, mealTypeLabel);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Грешка при генериране на PDF файла. Моля, опитайте отново.');
    }
  };

  const handleDownloadAllPDF = async () => {
    if (filteredRecipes.length === 0) {
      alert('Няма рецепти за изтегляне!');
      return;
    }
    try {
      await generateAllRecipesPDF(filteredRecipes, mealTypes);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Грешка при генериране на PDF файла. Моля, опитайте отново.');
    }
  };

  const renderRecipeContent = (content) => {
    const lines = content.split('\n');
    const elements = [];
    let currentList = null;
    let listItems = [];
    let keyIndex = 0;

    const flushList = () => {
      if (currentList && listItems.length > 0) {
        if (currentList.type === 'ul') {
          elements.push(
            <ul key={keyIndex++} className="recipe-text">
              {listItems}
            </ul>
          );
        } else {
          elements.push(
            <ol key={keyIndex++} className="recipe-text">
              {listItems}
            </ol>
          );
        }
        listItems = [];
        currentList = null;
      }
    };

    lines.forEach((line) => {
      const trimmedLine = line.trim();
      
      // Handle markdown headings
      if (trimmedLine.startsWith('## ')) {
        flushList();
        elements.push(<h3 key={keyIndex++} className="recipe-content-h3">{trimmedLine.substring(3)}</h3>);
        return;
      }
      if (trimmedLine.startsWith('### ')) {
        flushList();
        elements.push(<h4 key={keyIndex++} className="recipe-content-h4">{trimmedLine.substring(4)}</h4>);
        return;
      }
      if (trimmedLine.startsWith('# ')) {
        flushList();
        elements.push(<h2 key={keyIndex++} className="recipe-content-h2">{trimmedLine.substring(2)}</h2>);
        return;
      }
      
      // Handle bullet lists
      if (trimmedLine.startsWith('- ') || trimmedLine.startsWith('* ')) {
        if (currentList?.type !== 'ul') {
          flushList();
          currentList = { type: 'ul' };
        }
        listItems.push(<li key={keyIndex++} className="recipe-content-li">{trimmedLine.substring(2)}</li>);
        return;
      }
      
      // Handle numbered lists
      const numberedMatch = trimmedLine.match(/^\d+\.\s+(.+)$/);
      if (numberedMatch) {
        if (currentList?.type !== 'ol') {
          flushList();
          currentList = { type: 'ol' };
        }
        listItems.push(<li key={keyIndex++} className="recipe-content-li">{numberedMatch[1]}</li>);
        return;
      }
      
      // Non-list line - flush any current list
      flushList();
      
      // Handle bold text (**text**)
      if (trimmedLine.includes('**')) {
        const parts = trimmedLine.split(/(\*\*.*?\*\*)/g);
        elements.push(
          <p key={keyIndex++}>
            {parts.map((part, partIndex) => {
              if (part.startsWith('**') && part.endsWith('**')) {
                return <strong key={partIndex}>{part.slice(2, -2)}</strong>;
              }
              return <span key={partIndex}>{part}</span>;
            })}
          </p>
        );
        return;
      }
      
      // Regular paragraph
      if (trimmedLine) {
        elements.push(<p key={keyIndex++}>{trimmedLine}</p>);
        return;
      }
      
      // Empty line
      elements.push(<br key={keyIndex++} />);
    });

    // Flush any remaining list
    flushList();

    return elements;
  };

  const filteredRecipes = recipes.filter(recipe => {
    if (selectedMealType === 'all') {
      return true;
    }
    return recipe.mealType === selectedMealType;
  });

  return (
    <div className="recipe-book">
      <div className="recipe-book-header">
        <div className="recipe-book-title-section">
          <BookOpen size={32} />
          <div>
            <h2>Книга със здравословни рецепти</h2>
          </div>
        </div>
        <div className="recipe-book-actions">
          {!loading && filteredRecipes.length > 0 && (
            <button 
              className="btn-download-all"
              onClick={handleDownloadAllPDF}
              title="Изтегли всички рецепти като PDF"
            >
              <FileDown size={20} />
              Изтегли всички PDF
            </button>
          )}
        </div>
      </div>

      {loading && (
        <div className="loading">
          <div className="spinner"></div>
          <p>Зареждане на рецепти...</p>
        </div>
      )}

      {!loading && recipes.length > 0 && (
        <div className="recipe-filter">
          <div className="filter-label">
            <UtensilsCrossed size={18} />
            <span>Филтрирай по тип:</span>
          </div>
          <div className="filter-buttons">
            <button
              className={`filter-btn ${selectedMealType === 'all' ? 'active' : ''}`}
              onClick={() => setSelectedMealType('all')}
            >
              Всички
            </button>
            {mealTypes.map(type => (
              <button
                key={type.value}
                className={`filter-btn ${selectedMealType === type.value ? 'active' : ''}`}
                onClick={() => setSelectedMealType(type.value)}
              >
                {type.label}
              </button>
            ))}
          </div>
          {filteredRecipes.length !== recipes.length && (
            <div className="filter-results-count">
              Показани: {filteredRecipes.length} от {recipes.length} рецепти
            </div>
          )}
        </div>
      )}

      {!loading && filteredRecipes.length > 0 && (
        <div className="recipes-container">
          <div className="recipes-grid">
            {filteredRecipes.map((recipe) => (
              <Link 
                key={recipe.id} 
                to={`/recipes/${encodeURIComponent(recipe.filename)}`}
                className="recipe-card-link"
              >
                <div className="recipe-card">
                  {recipe.photo && (
                    <div className="recipe-photo">
                      <img src={recipe.photo} alt={recipe.title} />
                    </div>
                  )}
                  <div className="recipe-content">
                    <div className="recipe-header">
                      <h3 className="recipe-title">{recipe.title}</h3>
                      <ExternalLink size={18} className="recipe-link-icon" />
                    </div>
                    <div className="recipe-meta">
                      <span className="recipe-meal-type">
                        <UtensilsCrossed size={14} />
                        {getMealTypeLabel(recipe.mealType)}
                      </span>
                      <span className="recipe-author">
                        <User size={14} />
                        {recipe.author}
                      </span>
                    </div>
                    <div className="recipe-preview">
                      {recipe.content && (() => {
                        // Get first meaningful line (not empty, not heading, not list item)
                        const lines = recipe.content.split('\n');
                        const firstLine = lines.find(line => {
                          const trimmed = line.trim();
                          return trimmed && 
                                 !trimmed.startsWith('#') && 
                                 !trimmed.startsWith('-') && 
                                 !trimmed.startsWith('*') &&
                                 !trimmed.match(/^\d+\./);
                        });
                        const preview = firstLine ? firstLine.trim() : recipe.content.trim();
                        const displayText = preview.length > 150 ? preview.substring(0, 150) + '...' : preview;
                        return (
                          <p className="recipe-preview-text">{displayText}</p>
                        );
                      })()}
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      )}

      {!loading && filteredRecipes.length === 0 && recipes.length > 0 && (
        <div className="no-recipes">
          <div className="no-recipes-icon">🔍</div>
          <h3>Няма рецепти с избрания филтър</h3>
          <p>Моля, изберете друг тип ястие или кликнете "Всички" за да видите всички рецепти.</p>
        </div>
      )}

      {!loading && recipes.length === 0 && (
        <div className="no-recipes">
          <div className="no-recipes-icon">📖</div>
          <h3>Няма добавени рецепти</h3>
          <p>Добавете първата рецепта, за да започнете книгата със здравословни рецепти!</p>
          <p style={{ marginTop: '10px', fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
            Рецептите се зареждат от Markdown файлове в папката <code>public/recipes/</code>
          </p>
        </div>
      )}
    </div>
  );
}

export default RecipeBook;

