import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, User, UtensilsCrossed, FileDown, ExternalLink } from 'lucide-react';
import { parseRecipeMarkdown } from './utils/recipeParser';
import { generateAllRecipesPDF } from './utils/pdfGenerator';
import { recipeFiles } from './recipes/discovered';
import { getMealTypesFromRecipes, getMealTypeLabel, getDefaultMealTypes, MEAL_TYPE_LABELS } from './utils/mealTypes';
import { getRecipeImage } from './utils/recipeImage';
import './RecipeBook.css';

const RECIPES_DIR = '/recipes';

function RecipeBook() {
  const [recipes, setRecipes] = useState([]);
  const [mealTypes, setMealTypes] = useState(getDefaultMealTypes());
  const [loading, setLoading] = useState(true);
  const [selectedMealType, setSelectedMealType] = useState('all');

  useEffect(() => {
    loadRecipes();
  }, []);

  const loadRecipes = async () => {
    setLoading(true);
    try {
      // Use the auto-discovered recipe files list
      // This is generated by scripts/discover-recipes.js at build time
      
      // Load each recipe markdown file
      const loadedRecipes = await Promise.all(
        recipeFiles.map(async (filename) => {
          try {
            const response = await fetch(`${RECIPES_DIR}/${filename}`);
            if (!response.ok) {
              console.warn(`Could not load ${filename}`);
              return null;
            }
            const markdown = await response.text();
            const recipe = parseRecipeMarkdown(markdown);
            return {
              id: filename,
              filename: filename,
              ...recipe
            };
          } catch (error) {
            console.error(`Error loading ${filename}:`, error);
            return null;
          }
        })
      );

      // Filter out null values
      const validRecipes = loadedRecipes.filter(recipe => recipe !== null);
      setRecipes(validRecipes);
      
      // Extract meal types dynamically from loaded recipes
      const dynamicMealTypes = getMealTypesFromRecipes(validRecipes);
      if (dynamicMealTypes.length > 0) {
        setMealTypes(dynamicMealTypes);
      }
    } catch (error) {
      console.error('Error loading recipes:', error);
      setRecipes([]);
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadAllPDF = async () => {
    if (filteredRecipes.length === 0) {
      alert('Няма рецепти за изтегляне!');
      return;
    }
    try {
      await generateAllRecipesPDF(filteredRecipes, mealTypes);
    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Грешка при генериране на PDF файла. Моля, опитайте отново.');
    }
  };

  const stripMarkdown = (text) => {
    if (!text) return '';
    // Remove markdown formatting
    return text
      .replace(/\*\*(.*?)\*\*/g, '$1') // Bold **text**
      .replace(/\*(.*?)\*/g, '$1') // Italic *text*
      .replace(/##+ /g, '') // Headings ##
      .replace(/`(.*?)`/g, '$1') // Inline code `code`
      .replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1') // Links [text](url)
      .trim();
  };

  const filteredRecipes = recipes
    .filter(recipe => {
      if (selectedMealType === 'all') {
        return true;
      }
      return recipe.mealType === selectedMealType;
    })
    .sort((a, b) => {
      // First sort by mealType according to MEAL_TYPE_LABELS order
      const mealTypeOrder = Object.keys(MEAL_TYPE_LABELS);
      const indexA = mealTypeOrder.indexOf(a.mealType || '');
      const indexB = mealTypeOrder.indexOf(b.mealType || '');
      
      if (indexA !== indexB) {
        // If both are in MEAL_TYPE_LABELS, sort by index
        if (indexA !== -1 && indexB !== -1) {
          return indexA - indexB;
        }
        // If only one is in MEAL_TYPE_LABELS, it comes first
        if (indexA !== -1) return -1;
        if (indexB !== -1) return 1;
        // If neither is in MEAL_TYPE_LABELS, sort alphabetically
        const mealTypeA = (a.mealType || '').toLowerCase();
        const mealTypeB = (b.mealType || '').toLowerCase();
        return mealTypeA.localeCompare(mealTypeB);
      }
      
      // If same mealType, sort by title (ascending)
      const titleA = (a.title || '').toLowerCase();
      const titleB = (b.title || '').toLowerCase();
      return titleA.localeCompare(titleB);
    });

  return (
    <div className="recipe-book">
      <div className="recipe-book-header">
        <div className="recipe-book-title-section">
          <BookOpen size={32} />
          <div>
            <h2>Книга със здравословни рецепти</h2>
          </div>
        </div>
        <div className="recipe-book-actions">
          {!loading && filteredRecipes.length > 0 && (
            <button 
              className="btn-download-all"
              onClick={handleDownloadAllPDF}
              title="Изтегли всички рецепти като PDF"
            >
              <FileDown size={20} />
              Изтегли всички PDF
            </button>
          )}
        </div>
      </div>

      {loading && (
        <div className="loading">
          <div className="spinner"></div>
          <p>Зареждане на рецепти...</p>
        </div>
      )}

      {!loading && recipes.length > 0 && (
        <div className="recipe-filter">
          <div className="filter-label">
            <UtensilsCrossed size={18} />
            <span>Филтрирай по тип:</span>
          </div>
          <div className="filter-buttons">
            <button
              className={`filter-btn ${selectedMealType === 'all' ? 'active' : ''}`}
              onClick={() => setSelectedMealType('all')}
            >
              Всички
            </button>
            {mealTypes.map(type => (
              <button
                key={type.value}
                className={`filter-btn ${selectedMealType === type.value ? 'active' : ''}`}
                onClick={() => setSelectedMealType(type.value)}
              >
                {type.label}
              </button>
            ))}
          </div>
          {filteredRecipes.length !== recipes.length && (
            <div className="filter-results-count">
              Показани: {filteredRecipes.length} от {recipes.length} рецепти
            </div>
          )}
        </div>
      )}

      {!loading && filteredRecipes.length > 0 && (
        <div className="recipes-container">
          <div className="recipes-grid">
            {filteredRecipes.map((recipe) => (
              <Link 
                key={recipe.id} 
                to={`/recipes/${encodeURIComponent(recipe.filename)}`}
                className="recipe-card-link"
              >
                <div className="recipe-card">
                  <div className="recipe-photo">
                    <img src={getRecipeImage(recipe.photo, recipe.title)} alt={recipe.title} />
                  </div>
                  <div className="recipe-content">
                    <div className="recipe-header">
                      <h3 className="recipe-title">{recipe.title}</h3>
                      <ExternalLink size={18} className="recipe-link-icon" />
                    </div>
                    <div className="recipe-meta">
                      <span className="recipe-meal-type">
                        <UtensilsCrossed size={14} />
                        {getMealTypeLabel(recipe.mealType)}
                      </span>
                      <span className="recipe-author">
                        <User size={14} />
                        {recipe.author}
                      </span>
                    </div>
                    <div className="recipe-preview">
                      {recipe.content && (() => {
                        // Get first meaningful line (not empty, not heading, not list item)
                        const lines = recipe.content.split('\n');
                        const firstLine = lines.find(line => {
                          const trimmed = line.trim();
                          return trimmed && 
                                 !trimmed.startsWith('#') && 
                                 !trimmed.startsWith('-') && 
                                 !trimmed.startsWith('*') &&
                                 !trimmed.match(/^\d+\./);
                        });
                        const preview = firstLine ? firstLine.trim() : recipe.content.trim();
                        const strippedPreview = stripMarkdown(preview);
                        const displayText = strippedPreview.length > 150 ? strippedPreview.substring(0, 150) + '...' : strippedPreview;
                        return (
                          <p className="recipe-preview-text">{displayText}</p>
                        );
                      })()}
                    </div>
                  </div>
                </div>
              </Link>
            ))}
          </div>
        </div>
      )}

      {!loading && filteredRecipes.length === 0 && recipes.length > 0 && (
        <div className="no-recipes">
          <div className="no-recipes-icon">🔍</div>
          <h3>Няма рецепти с избрания филтър</h3>
          <p>Моля, изберете друг тип ястие или кликнете "Всички" за да видите всички рецепти.</p>
        </div>
      )}

      {!loading && recipes.length === 0 && (
        <div className="no-recipes">
          <div className="no-recipes-icon">📖</div>
          <h3>Няма добавени рецепти</h3>
          <p>Добавете първата рецепта, за да започнете книгата със здравословни рецепти!</p>
          <p style={{ marginTop: '10px', fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
            Рецептите се зареждат от Markdown файлове в папката <code>public/recipes/</code>
          </p>
        </div>
      )}
    </div>
  );
}

export default RecipeBook;

